### PR TITLE
Add virus scan to CI testing

### PR DESCRIPTION
**Pull request by petertix**
- Use the clamav virus scan tool

Signed-off-by: Peter Robinson <peter.timothy.robinson@gmail.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
What is it that we are scanning with this?  Is it anything that can at all reasonably carry and transmit a virus?

**Comment by jgrund** [comment]
This is very much a checkbox activity. By automating it, we don't need to do so prior to releasing new software.

**Comment by petertix** [comment]
The idea is to virus scan each repo with any new code changes. 
A manual scan of IML has shown no virus/malware issues.
By adding the virus scan to each PR, continuous virus protection will be the result.
 
The virus scanning tool: clamav is an opensource antivirus tool.

Below is a link that states the following:
"ClamAV ranked 13 out of 16 for Linux malware and viruses beating McAfee, Comodo and F-prot."

 http://www.linuxandubuntu.com/home/clamav-antivirus-scanner-for-linux-review-installation-usage

**Comment by brianjmurrell** [comment]
> This is very much a checkbox activity.

Understood.  But does _Clamav_ meet the checkbox requirements?

> By automating it, we don't need to do so prior to releasing new software.

Also understood.

**Comment by jgrund** [comment]
Yes, clamav is a scanner that meets the requirements.

**Comment by jgrund** [comment]
Closing in favor of #52

**Pull request closed without merging**
