### PR TITLE
Add Contributor docs to the IML Help Docs

### PR DESCRIPTION
**Pull request by petertix**
- Added a link to the README.md to point to the contrib docs
 - Created the directory, Contibutor_Docs
 - Appended each file with: cd_ to represent contributor docs
 - Added instructions for MacOS and Linux SSI tests

### CODE REVIEW

**Comment by jgrund** [comment]
Now that 2.10 is GA, you will need to go through and make sure the lustre urls reflect this.

**Comment by johnsonw** [comment]
I will pull this down and test the url's locally.

**Comment by johnsonw** [comment]
So before I go deep into this we are using "Manager for Lustre* software" throughout the docs. Do we need to add "Intel" in the front of all occurrences?

**Comment by johnsonw** [comment]
Example occurrence: 
```
Documents for contributing to the Manager for Lustre* software.
```

**Comment by petertix** [comment]
Will, you are correct. Instead of:

Manager for Lustre* software

The approved usage is: Intel® Manager for Lustre* software

I will make the changes.

**Comment by johnsonw** [comment]
Thanks Peter 👍

**Comment by johnsonw** [comment]
I've been looking through the links and marking any links that may need to be updated. Here is a list:

## ./docs/Contributor_Docs/cd_Monitored_Only_ZFS.md:
> https://github.com/intel-hpdd/intel-manager-for-lustre/releases/download/v4.0.0.0P3/iml-4.0.0.0.tar.gz

## ./docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.md
> https://github.com/intel-hpdd/intel-manager-for-lustre/releases/tag/v4.0.0.0P3

## ./docs/Install_Guide/ig_ch_08_manual_install.md
Need to verify that this is the link we should be using:
> https://build.hpdd.intel.com/job/lustre-manual/lastSuccessfulBuild/artifact/lustre_manual.xhtml\#part.installconfig

## ./docs/Install_Guide/ig_ch_05_install.md
Need to verify this link
> https://build.hpdd.intel.com/job/lustre-manual/lastSuccessfulBuild/artifact/lustre_manual.xhtml#part.installconfig

## ./docs/Install_Guide/ig_ch_04_pre_install.md
Need to verify this link
> https://build.hpdd.intel.com/job/lustre-manual/lastSuccessfulBuild/artifact/lustre_manual.xhtml#dbdoclet.50438216_15201

## ig_TOC.md
Need to verify this link
> https://build.hpdd.intel.com/job/lustre-manual/lastSuccessfulBuild/artifact/lustre_manual.xhtml#part.installconfig

## ./docs/api/Pkg_Guide.md
I think we want to make sure this is referencing EL7. Looks like it's linking to 6.
> https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/ch-yum.html

## ./docs/Contributor_Docs/cd_Contributor_Workflow.md
Looks like there might be an empty link here somewhere
image

**Comment by petertix** [comment]
Will, I made an update to add references to
Intel® Manager for Lustre* software
I also changed the links between pages to make them all consistent.
I did my push and then I saw your comments about the links.
I am working on those changes now.

**Comment by petertix** [comment]
Will,
I corrected the urls to point to: 
https://github.com/intel-hpdd/intel-manager-for-lustre/releases/download/4.0.0/iml-4.0.0.0.tar.gz

I corrected the the yum links to point to linux 7

I fixed the contributor workflow link.

The links pointing to the lustre manual still work. but I did not change them.

**Pull request merged**
