### PR TITLE
git subrepo clone git@github.com:intel-hpdd/module-tools.git ./include

### PR DESCRIPTION
**Pull request by johnsonw**
subrepo:
  subdir:   "include"
  merged:   "80d034f"
upstream:
  origin:   "git@github.com:intel-hpdd/module-tools.git"
  branch:   "master"
  commit:   "80d034f"
git-subrepo:
  version:  "0.4.0"
  origin:   "git@github.com:ingydotnet/git-subrepo.git"
  commit:   "74339e8"

### CODE REVIEW

**Comment by jgrund** [comment]
looks like jekyll + the recursive include in module-tools is causing the build to error.

```
jekyll 3.6.2 | Error:  Too many levels of symbolic links @ rb_sysopen - /home/travis/build/intel-hpdd/Online-Help/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include/include
```

**Comment by johnsonw** [comment]
@brianjmurrell https://github.com/intel-hpdd/Online-Help/pull/67

**Comment by johnsonw** [comment]
@brianjmurrell I think this is the ticket: https://github.com/intel-hpdd/Online-Help/issues/65

**Comment by brianjmurrell** [comment]
@johnsonw Ahhh.  I think #67 is what I was looking for.  We generally have been combining the commit that adds the subrepo and the bits that use it into a single PR, but there is no rule that we have to do that.  It just makes it more clear what benefit adding _module-tools_ is providing and that i just what I couldn't see here.

**Pull request merged**
